---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-aws-eks-get-ami-id-from-ssm-parameter
  annotations:
    render.crossplane.io/runtime: Development
spec:
  # The CLI ignores this package when using the Development runtime.
  # You can set it to any value.
  package: github.com/pauvilella/function-aws-eks-get-ami-id-from-ssm-parameter:v0.1.0
